name: Release new version

on:
  workflow_dispatch:
    inputs:
      majorRelease:
        required: false
        description: 'Trigger a major release (optional). Leave empty for regular release.'

jobs:
  integration-tests:
    uses: firebolt-db/firebolt-node-sdk/.github/workflows/integration-tests.yml@main

  publish:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:    
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 
        token: ${{ secrets.RELEASE_PAT }}
    
    - name: Set up node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        npm install 

    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        
    - name: Build
      run: |
        npm run build

    - name: Release (bump version, commiting changelog)
      run: |
        npm run release 

    - name: Publish to npm
      run: |
        npm publish
      env:
        USERNAME: ${{ secrets.NPM_USERNAME }}
        PASSWORD: ${{ secrets.NPM_PASSWORD }}

    - name: Push git tags
      run: |
        git push --follow-tags origin main
